GAMES_SERVER_ROUTE_NAME = 'games'
GAME_DETAIL_SERVER_ROUTE_NAME = 'game'

USERS_SERVER_ROUTE_NAME = 'users'
USER_DETAIL_SERVER_ROUTE_NAME = 'user'

CHATS_SERVER_ROUTE_NAME = 'chats'
CHAT_DETAIL_SERVER_ROUTE_NAME = 'chat'