GAMES_SERVER_ROUTE_NAME = 'games'
GAME_DETAIL_SERVER_ROUTE_NAME = 'games'
GAMES_INSTANCES_SERVER_ROUTE_NAME = 'games/instances'
GAMES_INSTANCES_DETAIL_SERVER_ROUTE_NAME = 'games/instances'

USERS_SERVER_ROUTE_NAME = 'users'
USER_DETAIL_SERVER_ROUTE_NAME = 'users'

CHATS_SERVER_ROUTE_NAME = 'chats'
CHAT_DETAIL_SERVER_ROUTE_NAME = 'chats'