GAMES_SERVER_ROUTE_NAME = 'games'
GAME_DETAIL_SERVER_ROUTE_NAME = 'games'

TREASURES_SERVER_ROUTE_NAME = 'treasures'
TREASURE_DETAIL_SERVER_ROUTE_NAME = 'treasures'

USERS_SERVER_ROUTE_NAME = 'users'
USER_DETAIL_SERVER_ROUTE_NAME = 'users'

CHATS_SERVER_ROUTE_NAME = 'chats'
CHAT_DETAIL_SERVER_ROUTE_NAME = 'chats'